export const UNITS_ACTION_TYPES = {
  LOAD_ALL_UNITS_START: "unit/LOAD_ALL_UNITS_START",
  LOAD_ALL_UNITS_SUCCESS: "unit/LOAD_ALL_UNITS_SUCCESS",
  LOAD_ALL_UNITS_FAILURE: "unit/LOAD_ALL_UNITS_FAILURE",
  CREATE_UNIT_START: "unit/CREATE_UNIT_START",
  CREATE_UNIT_SUCCESS: "unit/CREATE_UNIT_SUCCESS",
  CREATE_UNIT_FAILURE: "unit/CREATE_UNIT_FAILURE",
  UPDATE_UNIT_START: "unit/UPDATE_UNIT_START",
  UPDATE_UNIT_SUCCESS: "unit/UPDATE_UNIT_SUCCESS",
  UPDATE_UNIT_FAILURE: "unit/UPDATE_UNIT_FAILURE",
  DELETE_UNIT_START: "unit/DELETE_UNIT_START",
  DELETE_UNIT_SUCCESS: "unit/DELETE_UNIT_SUCCESS",
  DELETE_UNIT_FAILURE: "unit/DELETE_UNIT_FAILURE",
};
