export const GARMENT_TYPES_ACTION_TYPES = {
  LOAD_ALL_GARMENT_TYPES_START: "garmentType/LOAD_ALL_GARMENT_TYPES_START",
  LOAD_ALL_GARMENT_TYPES_SUCCESS: "garmentType/LOAD_ALL_GARMENT_TYPES_SUCCESS",
  LOAD_ALL_GARMENT_TYPES_FAILURE: "garmentType/LOAD_ALL_GARMENT_TYPES_FAILURE",
  CREATE_GARMENT_TYPE_START: "garmentType/CREATE_GARMENT_TYPE_START",
  CREATE_GARMENT_TYPE_SUCCESS: "garmentType/CREATE_GARMENT_TYPE_SUCCESS",
  CREATE_GARMENT_TYPE_FAILURE: "garmentType/CREATE_GARMENT_TYPE_FAILURE",
  UPDATE_GARMENT_TYPE_START: "garmentType/UPDATE_GARMENT_TYPE_START",
  UPDATE_GARMENT_TYPE_SUCCESS: "garmentType/UPDATE_GARMENT_TYPE_SUCCESS",
  UPDATE_GARMENT_TYPE_FAILURE: "garmentType/UPDATE_GARMENT_TYPE_FAILURE",
  DELETE_GARMENT_TYPE_START: "garmentType/DELETE_GARMENT_TYPE_START",
  DELETE_GARMENT_TYPE_SUCCESS: "garmentType/DELETE_GARMENT_TYPE_SUCCESS",
  DELETE_GARMENT_TYPE_FAILURE: "garmentType/DELETE_GARMENT_TYPE_FAILURE",
};
