export const BUYERS_ACTION_TYPES = {
  LOAD_ALL_BUYERS_START: "buyer/LOAD_ALL_BUYERS_START",
  LOAD_ALL_BUYERS_SUCCESS: "buyer/LOAD_ALL_BUYERS_SUCCESS",
  LOAD_ALL_BUYERS_FAILURE: "buyer/LOAD_ALL_BUYERS_FAILURE",
  CREATE_BUYER_START: "buyer/CREATE_BUYER_START",
  CREATE_BUYER_SUCCESS: "buyer/CREATE_BUYER_SUCCESS",
  CREATE_BUYER_FAILURE: "buyer/CREATE_BUYER_FAILURE",
  UPDATE_BUYER_START: "buyer/UPDATE_BUYER_START",
  UPDATE_BUYER_SUCCESS: "buyer/UPDATE_BUYER_SUCCESS",
  UPDATE_BUYER_FAILURE: "buyer/UPDATE_BUYER_FAILURE",
  DELETE_BUYER_START: "buyer/DELETE_BUYER_START",
  DELETE_BUYER_SUCCESS: "buyer/DELETE_BUYER_SUCCESS",
  DELETE_BUYER_FAILURE: "buyer/DELETE_BUYER_FAILURE",
};
