export const SUPPLIERS_ACTION_TYPES = {
  LOAD_ALL_SUPPLIERS_START: "supplier/LOAD_ALL_SUPPLIERS_START",
  LOAD_ALL_SUPPLIERS_SUCCESS: "supplier/LOAD_ALL_SUPPLIERS_SUCCESS",
  LOAD_ALL_SUPPLIERS_FAILURE: "supplier/LOAD_ALL_SUPPLIERS_FAILURE",
  CREATE_SUPPLIER_START: "supplier/CREATE_SUPPLIER_START",
  CREATE_SUPPLIER_SUCCESS: "supplier/CREATE_SUPPLIER_SUCCESS",
  CREATE_SUPPLIER_FAILURE: "supplier/CREATE_SUPPLIER_FAILURE",
  UPDATE_SUPPLIER_START: "supplier/UPDATE_SUPPLIER_START",
  UPDATE_SUPPLIER_SUCCESS: "supplier/UPDATE_SUPPLIER_SUCCESS",
  UPDATE_SUPPLIER_FAILURE: "supplier/UPDATE_SUPPLIER_FAILURE",
  DELETE_SUPPLIER_START: "supplier/DELETE_SUPPLIER_START",
  DELETE_SUPPLIER_SUCCESS: "supplier/DELETE_SUPPLIER_SUCCESS",
  DELETE_SUPPLIER_FAILURE: "supplier/DELETE_SUPPLIER_FAILURE",
};
