export const BASISES_ACTION_TYPES = {
  LOAD_ALL_BASISES_START: "basis/LOAD_ALL_BASISES_START",
  LOAD_ALL_BASISES_SUCCESS: "basis/LOAD_ALL_BASISES_SUCCESS",
  LOAD_ALL_BASISES_FAILURE: "basis/LOAD_ALL_BASISES_FAILURE",
  CREATE_BASIS_START: "basis/CREATE_BASIS_START",
  CREATE_BASIS_SUCCESS: "basis/CREATE_BASIS_SUCCESS",
  CREATE_BASIS_FAILURE: "basis/CREATE_BASIS_FAILURE",
  UPDATE_BASIS_START: "basis/UPDATE_BASIS_START",
  UPDATE_BASIS_SUCCESS: "basis/UPDATE_BASIS_SUCCESS",
  UPDATE_BASIS_FAILURE: "basis/UPDATE_BASIS_FAILURE",
  DELETE_BASIS_START: "basis/DELETE_BASIS_START",
  DELETE_BASIS_SUCCESS: "basis/DELETE_BASIS_SUCCESS",
  DELETE_BASIS_FAILURE: "basis/DELETE_BASIS_FAILURE",
};
