export const ADDRESS_ACTION_TYPES = {
  //   LOAD_ALL_ADDRESSES_START: "address/LOAD_ALL_ADDRESSES_START",
  //   LOAD_ALL_ADDRESSES_SUCCESS: "address/LOAD_ALL_ADDRESSES_SUCCESS",
  //   LOAD_ALL_ADDRESSES_FAILURE: "address/LOAD_ALL_ADDRESSES_FAILURE",
  LOAD_ADDRESSES_BY_ADDRESSID_START:
    "address/LOAD_ADDRESSES_BY_ADDRESSID_START",
  LOAD_ADDRESSES_BY_ADDRESSID_SUCCESS:
    "address/LOAD_ADDRESSES_BY_ADDRESSID_SUCCESS",
  LOAD_ADDRESSES_BY_ADDRESSID_FAILURE:
    "address/LOAD_ADDRESSES_BY_ADDRESSID_FAILURE",
  UPDATE_ADDRESS_START: "address/UPDATE_ADDRESS_START",
  UPDATE_ADDRESS_SUCCESS: "address/UPDATE_ADDRESS_SUCCESS",
  UPDATE_ADDRESS_FAILURE: "address/UPDATE_ADDRESS_FAILURE",
  CREATE_ADDRESS_START: "address/CREATE_ADDRESS_START",
  CREATE_ADDRESS_SUCCESS: "address/CREATE_ADDRESS_SUCCESS",
  CREATE_ADDRESS_FAILURE: "address/CREATE_ADDRESS_FAILURE",
  DELETE_ADDRESS_START: "address/DELETE_ADDRESS_START",
  DELETE_ADDRESS_SUCCESS: "address/DELETE_ADDRESS_SUCCESS",
  DELETE_ADDRESS_FAILURE: "address/DELETE_ADDRESS_FAILURE",
};
