export const COUNTRIES_ACTION_TYPES = {
  LOAD_ALL_COUNTRIES_START: "LOAD_ALL_COUNTRIES_START",
  LOAD_ALL_COUNTRIES_SUCCESS: "LOAD_ALL_COUNTRIES_SUCCESS",
  LOAD_ALL_COUNTRIES_FAILURE: "LOAD_ALL_COUNTRIES_FAILURE",
  CREATE_COUNTRY_START: "CREATE_COUNTRY_START",
  CREATE_COUNTRY_SUCCESS: "CREATE_COUNTRY_SUCCESS",
  CREATE_COUNTRY_FAILURE: "CREATE_COUNTRY_FAILURE",
  UPDATE_COUNTRY_START: "UPDATE_COUNTRY_START",
  UPDATE_COUNTRY_SUCCESS: "UPDATE_COUNTRY_SUCCESS",
  UPDATE_COUNTRY_FAILURE: "UPDATE_COUNTRY_FAILURE",
  DELETE_COUNTRY_START: "DELETE_COUNTRY_START",
  DELETE_COUNTRY_SUCCESS: "DELETE_COUNTRY_SUCCESS",
  DELETE_COUNTRY_FAILURE: "DELETE_COUNTRY_FAILURE",
};
