export const USER_ACTION_TYPES = {
  USER_REGISTER_START: "user/USER_REGISTER_START",
  USER_REGISTER_SUCCESS: "user/USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "user/USER_REGISTER_FAILURE",
  RESET_SIGNUP_STATE: "user/RESET_SIGNUP_STATE",
  USER_SIGNIN_START: "user/USER_SIGNIN_START",
  USER_SIGNIN_SUCCESS: "user/USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAILURE: "user/USER_SIGNIN_FAILURE",
  RESET_SIGNIN_STATE: "user/RESET_SIGNIN_STATE", // <-- Add this line
  USER_SIGNOUT_START: "user/USER_SIGNOUT_START",
  USER_SIGNOUT_SUCCESS: "user/USER_SIGNOUT_SUCCESS",
  USER_SIGNOUT_FAILURE: "user/USER_SIGNOUT_FAILURE",
  GET_USER_BY_EMAIL_START: "user/GET_USER_BY_EMAIL_START",
  GET_USER_BY_EMAIL_SUCCESS: "user/GET_USER_BY_EMAIL_SUCCESS",
  GET_USER_BY_EMAIL_FAILURE: "user/GET_USER_BY_EMAIL_FAILURE",
  UPDATE_USER_START: "user/UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "user/UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "user/UPDATE_USER_FAILURE",
};
