export const CURRENCIES_ACTION_TYPES = {
  LOAD_ALL_CURRENCIES_START: "LOAD_ALL_CURRENCIES_START",
  LOAD_ALL_CURRENCIES_SUCCESS: "LOAD_ALL_CURRENCIES_SUCCESS",
  LOAD_ALL_CURRENCIES_FAILURE: "LOAD_ALL_CURRENCIES_FAILURE",
  CREATE_CURRENCY_START: "CREATE_CURRENCY_START",
  CREATE_CURRENCY_SUCCESS: "CREATE_CURRENCY_SUCCESS",
  CREATE_CURRENCY_FAILURE: "CREATE_CURRENCY_FAILURE",
  UPDATE_CURRENCY_START: "UPDATE_CURRENCY_START",
  UPDATE_CURRENCY_SUCCESS: "UPDATE_CURRENCY_SUCCESS",
  UPDATE_CURRENCY_FAILURE: "UPDATE_CURRENCY_FAILURE",
  DELETE_CURRENCY_START: "DELETE_CURRENCY_START",
  DELETE_CURRENCY_SUCCESS: "DELETE_CURRENCY_SUCCESS",
  DELETE_CURRENCY_FAILURE: "DELETE_CURRENCY_FAILURE",
};
